patroni to pgo migration
bcgov/cas-metabase pull request #125
Opened 2024-08-08 21:17 UTC by pbastia

2024-08-23 18:13 UTC, dleard requested changes
Looks great! A couple of small changes needed

2024-08-23 18:13 UTC, dleard commented on helm/cas-metabase/templates/cron-prod-test-restore.yaml
> +                  alueFrom:
```suggestion
                  valueFrom:
```

2024-08-23 18:13 UTC, dleard commented on helm/cas-metabase/values.yaml
> +    host: cas-metabase-patroni.9212c9-dev.svc.cluster.local
Should "host" be set to ~ & specified in each values-environment yaml file?

2024-09-04 21:54 UTC, dleard approved these changes
:100: Let me know when you want to run this!

2024-09-04 22:06 UTC, pbastia commented
@dleard it's been run on -dev. It should automatically run on -test upon merging to `main`, we'll need to monitor that closely

2024-09-04 22:06 UTC, merged